version: '3.8'

services:
  adsvnzla:
    build: .
    container_name: adsvnzla-app
    ports:
      - "8085:80"
    restart: always
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
